module.exports = {
  purge: ['./pages/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}'],
  darkMode: false, // or 'media' or 'class'
  theme: {
    extend: {
      backgroundColor: theme => ({
        'as-grey': '#E1E2E2',
        'theme-color': '#1C1C1C',
        'ass-theme-color': '#E1E2E2',
        'ass-background-color': '#CACCC9',
        'ass-bgcolor-orange': '#FB8122',
        'ass-bgcolor-black': '#1D2228',
        'mgbd-red': '#EC221C',
        'mgbd-grey': '#2e2e2e',
        'gnf-primary': '#1B232A',
        'gnf-secondary': '#F9A34F',
        'uat-primary': '#1A1A1A',
        'yale-primary': '#FBE82D',
        'yale-grey': '#464646',
        'pj-orange': '#F07A18',
        'pj-orange-fruit': '#ED8E40',
        'pj-yellow-fruit': '#F8D25A',
        'pj-green-fruit': '#A5D15D',
        'pj-grey': '#E1E1E1',
        'pj-primary': '#F6F5FA',
        'pj-secondary': '#575757',
        'paradise-primary': '#F2B846',
        'paradise-primary-light': '#F8DBA2',
        'paradise-secondary': '#013953',
        'lucas-grey': '#AAAAAA',
        'lucas-blue': '#2D3A66',
        'pm-orange': '#FF6138',
        'pm-blue': '#141733',
      }),

      textColor: theme => ({
        'ass-primary': '#FB8122',
        'gnf-primary': '#F9A34F',
        'gnf-grey': '#999999',
        'mgbd-red':'#EC221C',
        'mgbd-grey': '#939292',
        'yale-grey': '#777777',
        'paradise-orange': '#F2B846',
        'paradise-grey': '#616161',
        'pm-orange': '#FF6138',
    }), 

      fontSize: {
        'xs': '.75rem',
        'sm': '.875rem',
        'tiny': '.875rem',
        'base': '1rem',
        'lg': '1.125rem',
        'xl': '1.25rem',
        '2xl': '1.5rem',
        '3xl': '1.875rem',
        '4xl': '2.25rem',
        '5xl': '3rem',
        '6xl': '4rem',
        '7xl': '5rem',
        '8xl': '6rem',
        '9xl': '7rem',
        '10xl': '8rem',
        '11xl': '9rem',
      },

      fontFamily:{
        'ass-modern': ['MOD20'],
        'ass-brittany': ['BrittanySignatureRegular, Brittany Signature'],
        'ass-raleway': ['Raleway'],
      },

    },
  },
  variants: {
    extend: {},
  },
  plugins: [],
}
